### PR TITLE
Rebased version of PR #13

### PR DESCRIPTION
**Pull request by reneroth**
includes latest improvements by @EricOdmyr

- General cleanup of redundant and unused files
- Home menu has been restructured
- Refactoring of shared image/css/js resources
- Removed dependency on jQuery, rewrote script in vanilla js
- Static assets have been greatly compressed without loss of quality

Also note that I have removed the English version from the repo and replaced with a link to the official website, to be more compliant of the MIT license. The license information still needs to be adjusted to exempt the included cyrillic font files.

### CODE REVIEW

**Comment by brugnara** [comment]
This is a huge refactor. I have to check a lot of changes before merging.
Thanks for your help.

**Comment by brugnara** [comment]
@RRorg ok then.

- the "here" link is not visible. It appears only after a click, maybe some style is missing.
- the russian folder must not change name because github.io doesn't allow a folder to be named `russian`, don't ask why. It simply doesn't work, we have tried lot of times before, so it should be called `russian2` like now.
- you forgot naming me and @BrightSoul for the Italian part, as contributors
- the readme has a typo: "Inofficial" instead of "Unofficial".

Thank you for your help.

**Comment by reneroth** [comment]
Give me a few hours, still in the middle of something, but will fix the issues! Thank you for taking a look :)

**Comment by brugnara** [comment]
@RRorg before you start, I'm going to merge the german repo on master 👍

**Comment by brugnara** [comment]
@jaramir is also an Italian contributor I forgot to mention before.

**Comment by brugnara** [comment]
@RRorg I have merged all languages, so now you should see 3 folders with changes. The changes are very minimalistic but needed as the main page was not updated with the great work other guys made to spanish and german folders.

**Comment by reneroth** [comment]
@brugnara Sorry for the wait, everything should be up to date and ready to merge now!

**Comment by brugnara** [comment]
@RRorg I don't know why I missed this, sorry for the very long delay and thank you for the great job.

**Comment by reneroth** [comment]
oh do not worry, it happens to the best of us :D

**Pull request merged**
