### PR TITLE
Croatian translation

### PR DESCRIPTION
**Pull request by thevoiddancer**
Hi @brugnara , I've created a Croatian translation, as the one linked in official pinned thread on Steam forums is no longer available.

However, I'm not sure about creating the PDF. First the relative link for assets seems to be off ("/assets" as opposed to "../assets") and even when I update the links I get extremely huge SVG images that render the whole PDF unreadable. What am I missing here? :)

### CODE REVIEW

**Comment by brugnara** [comment]
Thank you for you effort!

It should be enough to print as a PDF the webpage.

Isn't working as expected?

**Comment by thevoiddancer** [comment]
Yes, you are absolutely correct! I tried opening it on another computer and everything works fine. I won't even pretend I could understand why it didn't work. :D I'll print the PDF and update the pull request in a couple of days - I got some more people to playtest/proofread it.

**Comment by thevoiddancer** [comment]
Hi @brugnara , the PDF file is attached, you can merge this.

**Comment by brugnara** [comment]
Good one!

Am I wrong if I say the link in the index.html is missing? 

You may want to add it here, in alphabetical order: https://github.com/bombmanual/bombmanual.github.io/blob/master/index.html

You may also want to add your name in the Readme, if you'd like to.

Thanks so much for your work.

**Comment by thevoiddancer** [comment]
Yeah, you're right @brugnara , I was focused on getting the PDF. It's added now.

**Pull request merged**
