### PR TITLE
Dutch version 2.0

### PR DESCRIPTION
**Pull request by Rajzin**
I made dozens of corrections and improvements to the Dutch version. I'm not sure how to best convert the new translation to PDF though, so the PDF is still old.

changes:
- fixed several grammatical mistakes
- fixed several typos
- rephrased many parts to be clearer, more faithful to the original wording, and/or more natural Dutch. This includes changes to the used terminology, such as:
	* two instances of "tijdsklok" changed to "timer" to match the rest of the manual.
	* changed the translation for "Venting Steam" from "Afreageren" (taking it out on someone) to "Gas afblazen" (venting gas)
	* previously, the same word "knop" was used to translate both "button" and "knob". I changed the translation for "The Button" to "de Grote Knop" (the Big Button), and the translation for "knob" to the more accurate translation "draaiknop" (literally "turning button")
- added translations between brackets to words whose meanings are important to understanding the manual, or for navigating the in-game menus. This includes:
	* "Veeleisende modules" (Needy modules) on page 3 and page 17
	* "UP" on page 20 (Kobs)
- on page 18 (Venting Gas), I added a list of texts that can appear on the module display and their Dutch translations. This has minor spoilers for beginning players, but is critical for players who don't understand what "Detonate?" means.

- corrected morse code chart translation
- added Dutch versions of ButtonComponent.svg, venndiagram.svg, NeedyVentComponent.svg, and WhosOnFirstComponent.svg
- converted text to vector in SVG images to make sure the Special Elite font is displayed. (Quite possibly I didn't do this the most efficient way, so sorry for the relatively large file sizes)

### CODE REVIEW

**Comment by brugnara** [comment]
Hi @Rajzin .

What a huge commit you made, a big thank you!

For the PDF I really don't how other guys generated but I guess they do a "print to PDF".  Let me tag @berna1995 as a confirm for this.

I'll wait just some time, maybe you can push the PDF too and the Dutch will be 100% consistent.

Again, thank you!

**Comment by berna1995** [comment]
Yes, i can confirm that.
I just used the "print to PDF" to generate the PDF file.

**Comment by Rajzin** [comment]
@I also didn't really figure out how to view the final product with CSS formatting and images and all. 




↑ This is all I managed to get, and of course I'm not PDFing that. What do I do? I'm not very experienced with HTML, I'm afraid. I was hoping it would just kind of work when I put all the modified files in GitHub.

Either way, you're welcome! It's a fun project, and the new Dutch version will be useful for playing with family and friends.

**Comment by brugnara** [comment]
I'll merge, we can do the PDF version when this is merged. Any help is apreciated :)

**Pull request merged**
