### PR TITLE
Swedish button redirect

### PR DESCRIPTION
**Pull request by EricOdmyr**
The Swedish button now redirects to my own github page for the Swedish
manual.

### CODE REVIEW

**Comment by brugnara** [comment]
What do you think about putting your effort in this repo?
In a future, if you are going to change your github.io page, we are going to lose the "swedish" translation and it's a pity.
Let me know what you think and thanks for your work.

**Comment by mariansam** [comment]
This is opened for more than a year, I think, we should pull @EricOdmyr's [files](https://github.com/EricOdmyr/bombmanual.github.io/tree/master/swedish) into this manually. Link to different website is unnecessary.

**Comment by brugnara** [comment]
@mariansam thank you for your contribute. Do you think it is possible to make a "linked folder" to @EricOdmyr 's repo without manually copying files?

**Comment by mariansam** [comment]
I will try.

**Comment by mariansam** [comment]
Ok, I tried. I can't make it... I think, we should just copy the files manually. I he has it somehow different, his `index.html` has only 24 lines.

**Comment by brugnara** [comment]
@mariansam I did the trick.

For your information, here's a quick guide ;) https://blog.github.com/2016-02-01-working-with-submodules/

```
git submodule add https://github.com/svenskbombmanual/svenskbombmanual.github.io swedish
```

@EricOdmyr I referenced your repo into this one.

**Pull request closed without merging**
