### PR TITLE
Refactoring and fixes

### PR DESCRIPTION
**Pull request by reneroth**
- General cleanup of redundant and unused files
- Home menu has been restructured
- Refactoring of shared image/css/js resources
- Removed dependency on jQuery, rewrote script in vanilla js
- Static assets have been greatly compressed without loss of quality

Also note that I have removed the English version from the repo and replaced with a link to the official website, to be more compliant of the MIT license. The license information still needs to be adjusted to exempt the included cyrillic font files.

### CODE REVIEW

**Comment by reneroth** [comment]
Also please add the main contributors to the Readme.md

**Comment by brugnara** [comment]
@RRorg this can not be merged. Can you please fix?

Also, GitHub automatically shows the contributors to a project, so redounding them in the Readme is unneeded effort, in my opinion: https://github.com/bombmanual/bombmanual.github.io/graphs/contributors

**Comment by reneroth** [comment]
I fixed all conflicts 🙂  @brugnara 

You're right about the contributors thing, so I only mentioned external translators in the Readme file (Steamcommunity, etc)

**Comment by brugnara** [comment]
Great job, thank you for your work.

After your explanation, I totally agree with you and the Readme file. 👍

**Comment by brugnara** [comment]
@RRorg I noticed russian folder is broken. I remember I had to rename russian2 because named russian, it simply doesn't work and I really don't know why.

For now I'll revert this merge. So far so good, I prefer the red layout proposed by #11 . What do you think about?

**Comment by brugnara** [comment]
@RRorg the problem about russian folder is when you see from here: http://bombmanual.github.io/

The way it is now is fine.

**Comment by reneroth** [comment]
ah good call, the layout by @EricOdmyr is really cool, give me a day or two to incorporate it into my design changes! :) 
It is really strange with the russian folder - but if that's the way to fix it for now it'll have to do :/

**Pull request merged**
