### PR TITLE
German: Correct grammar/spelling, rephrase for better text quality

### PR DESCRIPTION
**Pull request by MergingMonkey**
- Correct grammar (most obviously the wrong title: https://de.wikipedia.org/wiki/Leerzeichen_in_Komposita)
- Correct typos
- Replace some wrong words
- Complete some words missing characters
- Rephrasing of some sentences for more fluid reading, less repetition and better comprehension
- Replace "Knubbel" with the more factual "Drehknauf"
- Rephrase the lengthy appendix heading words

### CODE REVIEW

**Comment by brugnara** [comment]
@Intruder66 thank you for your effort.

I can not check this pull request because I don't speak German so I'm tagging someone else.

@RRorg @FroznMine

**Comment by reneroth** [comment]
This PR gets an OK from me.

It's some very nice work, and does a great job at making the German translation seem less amateurish and more professional. Thank you for your effort! :)

**Comment by brugnara** [comment]
Thanks to both of you 👍

**Comment by MergingMonkey** [comment]
Thank you two for the fast review!

**Pull request merged**
