### PR TITLE
minor improvements, see description

### PR DESCRIPTION
**Pull request by jmgraeffe**
I've made some improvements, hopefully you like them. 😄 

- added PDF versions for English and German (would fix/work around #17 and #9) 
- added download buttons for PDF

You can see a preview of the front page here: https://j0nnib0y.github.io/bombmanual-printable/
(The changes I made to the actual manual pages there are not included in this pull request.)

### CODE REVIEW

**Comment by MergingMonkey** [comment]
@L3viathan 

Long overdue changes in my point of view. Couldn't print out the current version correctly with several browsers...

**Comment by brugnara** [comment]
@j0nnib0y thank you for your help. Very appreciated. I have just merged a branch and this now conflicts. Can you do a quick check?

**Comment by jmgraeffe** [comment]
I think most things I implemented are done by the pull request you merged with before. I will create a new pull request for the additional PDFs I've created for this repository.

**Comment by brugnara** [comment]
GTK. 👍

**Comment by jmgraeffe** [comment]
@brugnara My German PDF is ~24 MB, since it's printed out with browser tools. Is there any template or script which does the PDF creation in text form? Or are they all self-made?

**Comment by brugnara** [comment]
@j0nnib0y I really don't know how they do the PDF version.

I only did the HTML version.. Maybe they use some program to edit the original PDF, maybe I am wrong.

**Pull request closed without merging**
